services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres"
    container_name: "pg_service"
    environment:
      - POSTGRES_DB=cars
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    volumes:
      - cars-volume:/var/lib/postgresql/data
    ports:
      - 5434:5432
    restart: unless-stopped
volumes:
  cars-volume: